export const cardsData = [
    {
        id: 1,
        image: "https://i.ibb.co/ym4Xs254/nutrition.png",
        title: "Nutrition",
        duration: "12/90",
        unit: "weekly",
        description: "A plant-predominant, whole food diet helps prevent and manage chronic diseases effectively.",
    },
    {
        id: 2,
        image: "https://i.ibb.co/tMh9QCv0/pe.png",
        title: "Physical activity",
        duration: "32",
        unit: "minutes",
        description: "Engaging in regular movement supports cardiovascular health and enhances overall fitness.",
    },
    {
        id: 3,
        image: "https://i.ibb.co/Zb5JpWd/rs.png",
        title: "Restorative sleep",
        duration: "8",
        unit: "hours",
        description: "Quality sleep is foundational to mental clarity, emotional regulation, and physical repair.",
    },
    {
        id: 4,
        image: "https://cdn.corenexis.com/i/mm/ju12/5CZ6yH.png?token=eaf433ce27fb7d990de6c1f37c0fa746",
        title: "Stress management",
        duration: "15",
        unit: "minutes",
        description: "Mindfulness, journaling, and breathing practices are effective tools for managing daily stress.",
    },
    {
        id: 5,
        image: "https://cdn.corenexis.com/i/mm/ju12/fm54ew.png?token=eaf433ce27fb7d990de6c1f37c0fa746",
        title: "Social connection",
        duration: "1",
        unit: "interaction/day",
        description: "Maintaining meaningful relationships helps reduce anxiety and promotes emotional balance.",
    },
    {
        id: 6,
        image: "https://cdn.corenexis.com/i/mm/ju12/OJHqo8.png?token=eaf433ce27fb7d990de6c1f37c0fa746",
        title: "Substance abuse",
        duration: "0",
        unit: "instances",
        description: "Avoiding tobacco, alcohol, and recreational drugs supports long-term health and well-being.",
    },
];